package com.my.domain;
// Generated Aug 25, 2015 11:15:05 AM by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import java.util.Date;



/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer commentId;
	private Bug bug;
	private User user;
	private Comment referComment;
	private String content;
	private Timestamp pubTime;

	public Comment() {
	}

	public Comment(Bug bug, User user, String content, Timestamp pubTime) {
		this.bug = bug;
		this.user = user;
		this.content = content;
		this.pubTime = pubTime;
	}

	public Comment(Bug bug, User user, Comment referComment, String content, Timestamp pubTime) {
		this.bug = bug;
		this.user = user;
		this.referComment = referComment;
		this.content = content;
		this.pubTime = pubTime;
	}

	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	public Bug getBug() {
		return this.bug;
	}

	public void setBug(Bug bug) {
		this.bug = bug;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Timestamp getPubTime() {
		return this.pubTime;
	}

	public void setPubTime(Timestamp pubTime) {
		this.pubTime = pubTime;
	}
	
	public Comment getReferComment() {
		return referComment;
	}

	public void setReferComment(Comment referComment) {
		this.referComment = referComment;
	}

}
