package com.my.domain;
// Generated Aug 25, 2015 11:15:05 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Assignment generated by hbm2java
 */
public class Assignment implements java.io.Serializable {

	private Integer assignId;
	private Bug bug;
	private User userByAssignedUserId;
	private User userByOperateUserId;
	private String status;
	private Date beginTime;
	private Date endTime;

	public Assignment() {
	}

	public Assignment(Bug bug, User userByAssignedUserId, User userByOperateUserId, String status, Date beginTime) {
		this.bug = bug;
		this.userByAssignedUserId = userByAssignedUserId;
		this.userByOperateUserId = userByOperateUserId;
		this.status = status;
		this.beginTime = beginTime;
	}

	public Assignment(Bug bug, User userByAssignedUserId, User userByOperateUserId, String status, Date beginTime,
			Date endTime) {
		this.bug = bug;
		this.userByAssignedUserId = userByAssignedUserId;
		this.userByOperateUserId = userByOperateUserId;
		this.status = status;
		this.beginTime = beginTime;
		this.endTime = endTime;
	}

	public Integer getAssignId() {
		return this.assignId;
	}

	public void setAssignId(Integer assignId) {
		this.assignId = assignId;
	}

	public Bug getBug() {
		return this.bug;
	}

	public void setBug(Bug bug) {
		this.bug = bug;
	}

	public User getUserByAssignedUserId() {
		return this.userByAssignedUserId;
	}

	public void setUserByAssignedUserId(User userByAssignedUserId) {
		this.userByAssignedUserId = userByAssignedUserId;
	}

	public User getUserByOperateUserId() {
		return this.userByOperateUserId;
	}

	public void setUserByOperateUserId(User userByOperateUserId) {
		this.userByOperateUserId = userByOperateUserId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

}
