package com.my.domain;
// Generated Aug 25, 2015 11:15:05 AM by Hibernate Tools 4.3.1

/**
 * MemberId generated by hbm2java
 */
public class MemberId implements java.io.Serializable {

	private int userId;
	private int projectId;

	public MemberId() {
	}

	public MemberId(int userId, int projectId) {
		this.userId = userId;
		this.projectId = projectId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}
	
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MemberId))
			return false;
		MemberId castOther = (MemberId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getProjectId() == castOther.getProjectId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getProjectId();
		return result;
	}

}
