package com.my.domain;
// Generated Aug 24, 2015 9:38:26 AM by Hibernate Tools 4.3.1

/**
 * Image generated by hbm2java
 */
public class UploadFile implements java.io.Serializable
{

	private Integer	fileId;
	private Bug		bug;
	private String	savePath;
	private boolean isImage;
	
	public UploadFile()
	{
	}

	public UploadFile(Bug bug, String savePath)
	{
		this.bug = bug;
		this.savePath = savePath;
	}

	public Integer getFileId()
	{
		return fileId;
	}

	public void setFileId(Integer fileId)
	{
		this.fileId = fileId;
	}

	public Bug getBug()
	{
		return this.bug;
	}

	public void setBug(Bug bug)
	{
		this.bug = bug;
	}

	public String getSavePath()
	{
		return this.savePath;
	}

	public void setSavePath(String savePath)
	{
		this.savePath = savePath;
	}

	public boolean getIsImage()
	{
		return isImage;
	}

	public void setIsImage(boolean isImage)
	{
		this.isImage = isImage;
	}

	
}
